kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fluentbit-storage
reclaimPolicy: Delete
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: logs-pvc
    labels:
       app: fluent-bit-logging
spec:
  storageClassName: fluentbit-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pv
  labels:
    app: fluent-bit-logging
spec:
  storageClassName: fluentbit-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: elasticsearch
    name: logs-pvc
  hostPath:
    path: "/mnt/data/my-database"
    type: DirectoryOrCreate




